# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcPlugin/protos/base_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GrpcPlugin/protos/base_proto.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x01\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x1f\n\x06method\x18\x02 \x01(\x0e\x32\x0f.Request.Method\x12%\n\x04\x62ody\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"0\n\x06Method\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x12\x07\n\x03PUT\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\"g\n\x08Response\x12\x0e\n\x06result\x18\x04 \x01(\x08\x12\x0f\n\x07message\x18\x05 \x01(\t\x12%\n\x04\x62ody\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0bstatus_code\x18\x07 \x01(\x03\x32\x30\n\x0bHTTPHandler\x12!\n\x08\x44ispatch\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_REQUEST_METHOD = _REQUEST.enum_types_by_name['Method']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'GrpcPlugin.protos.base_proto_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'GrpcPlugin.protos.base_proto_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_HTTPHANDLER = DESCRIPTOR.services_by_name['HTTPHandler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=69
  _REQUEST._serialized_end=213
  _REQUEST_METHOD._serialized_start=165
  _REQUEST_METHOD._serialized_end=213
  _RESPONSE._serialized_start=215
  _RESPONSE._serialized_end=318
  _HTTPHANDLER._serialized_start=320
  _HTTPHANDLER._serialized_end=368
# @@protoc_insertion_point(module_scope)
