# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61se_proto.proto\x1a\x1cgoogle/protobuf/struct.proto\"V\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x17\n\x06method\x18\x02 \x01(\x0e\x32\x07.Method\x12%\n\x04\x62ody\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x86\x01\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x03\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x12*\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x01\x88\x01\x01\x42\n\n\x08_messageB\x07\n\x05_data*0\n\x06Method\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x12\x07\n\x03PUT\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x32\x30\n\x0bGrpcHandler\x12!\n\x08\x44ispatch\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METHOD._serialized_start=275
  _METHOD._serialized_end=323
  _REQUEST._serialized_start=50
  _REQUEST._serialized_end=136
  _RESPONSE._serialized_start=139
  _RESPONSE._serialized_end=273
  _GRPCHANDLER._serialized_start=325
  _GRPCHANDLER._serialized_end=373
# @@protoc_insertion_point(module_scope)
